spring:
  application:
    name: config
  cloud:
    config:
      server:
        bootstrap: true
        native:
          search-locations: classpath:/shared
  profiles:
     active: native

server:
  port: 8888

management:
  context-path: /admin
  security:
    enabled: false